Repository MartinKwon94/Limjinlok, pull requests merged in 2023-09, with the labels that each got.

#3 UI/mypage
  app/build.gradle
  app/src/main/java/com/example/limjinlok/MainActivity.kt
  app/src/main/java/com/example/limjinlok/MyPageFragment.kt
  app/src/main/res/drawable/bonobono.jpg
  app/src/main/res/drawable/edit_10.xml
  app/src/main/res/drawable/mp_rainbow.xml
  app/src/main/res/drawable/mp_stroke_rect.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/page_item.xml
  app/src/main/res/values/strings.xml
  contact_image/Edit-10.svg
  contact_image/bonobono.jpg
Labels: enhancement

#4 UI 완료
  app/build.gradle
  app/src/main/java/com/example/limjinlok/Contactlist.kt
  app/src/main/java/com/example/limjinlok/placeholder/PlaceholderContent.kt
  app/src/main/res/drawable/selector_image_button.xml
  app/src/main/res/layout/fragment_contactlist.xml
  app/src/main/res/layout/item_contactlist.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: first freature

#1 mainactivity ui 추가
  app/src/main/java/com/example/limjinlok/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: enhancement

#2 UI/contact detail
  app/build.gradle
  app/src/main/java/com/example/limjinlok/ContactDetailFragment.kt
  app/src/main/res/drawable/cd_border.xml
  app/src/main/res/layout/fragment_contact_detail.xml
Labels: enhancement, good first issue

#5 UI/mainactivityfab
  app/src/main/res/drawable/ic_baseline_add.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#7 Dialog 생성
  app/src/main/java/com/example/limjinlok/Dialog.kt
  app/src/main/res/drawable/sample.png
  app/src/main/res/layout/dialog.xml
Labels: documentation, first freature

#8 add tablayout and viewpager
  app/src/main/java/com/example/limjinlok/Dialog.kt
  app/src/main/java/com/example/limjinlok/MainActivity.kt
  app/src/main/java/com/example/limjinlok/MainTabsModel.kt
  app/src/main/java/com/example/limjinlok/MainViewPagerAdapter.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_contactlist.xml
  app/src/main/res/layout/item_contactlist.xml
Labels: enhancement

#9 Feature/Bundle
  app/src/main/java/com/example/limjinlok/ContactDetailFragment.kt
  app/src/main/java/com/example/limjinlok/Contactlist.kt
  app/src/main/java/com/example/limjinlok/MyPageFragment.kt
  app/src/main/res/drawable/mp_stroke_rect.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/page_item.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#13 Hotfix/binding
  app/src/main/java/com/example/limjinlok/ContactDetailFragment.kt
  app/src/main/java/com/example/limjinlok/Contactlist.kt
  app/src/main/java/com/example/limjinlok/MyPageFragment.kt
Labels: bug

#18 pass data to contact list fragment 기능 추가
  app/src/main/java/com/example/limjinlok/ContactlistAdapter.kt
  app/src/main/java/com/example/limjinlok/ContactlistFragment.kt
  app/src/main/java/com/example/limjinlok/MainActivity.kt
Labels: enhancement

#19 mainactivity fav 위치 조정
  app/src/main/res/drawable/ic_baseline_add.xml
  app/src/main/res/layout/activity_main.xml
Labels: bug

#22 UI/dialog
  app/src/main/java/com/example/limjinlok/Dialog.kt
Labels: documentation

#23 contactdetail activity 변경
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/limjinlok/ContactDetailActivity.kt
  app/src/main/java/com/example/limjinlok/ContactDetailFragment.kt
  app/src/main/res/layout/activity_contact_detail.xml
Labels: enhancement

#25 contactlistitemclick event 추가
  app/src/main/java/com/example/limjinlok/ContactDetailActivity.kt
  app/src/main/java/com/example/limjinlok/ContactDetailAdapter.kt
  app/src/main/java/com/example/limjinlok/ContactListAdapter.kt
  app/src/main/java/com/example/limjinlok/ContactListFragment.kt
  app/src/main/java/com/example/limjinlok/ContactViewHolder.kt
  app/src/main/java/com/example/limjinlok/ContactViewHolderGrid.kt
  app/src/main/java/com/example/limjinlok/ContactViewHolderOdd.kt
  app/src/main/java/com/example/limjinlok/MyPageFragment.kt
Labels: enhancement

#29 Feature/dialogupdate
  app/src/main/java/com/example/limjinlok/ContactListAdapter.kt
  app/src/main/java/com/example/limjinlok/ContactListFragment.kt
  app/src/main/java/com/example/limjinlok/Dialog.kt
  app/src/main/java/com/example/limjinlok/MainActivity.kt
Labels: documentation

#30 passto data mp
  app/src/main/java/com/example/limjinlok/ContactDetailActivity.kt
  app/src/main/java/com/example/limjinlok/ContactDetailAdapter.kt
  app/src/main/java/com/example/limjinlok/ContactListAdapter.kt
  app/src/main/java/com/example/limjinlok/MainActivity.kt
  app/src/main/java/com/example/limjinlok/MyPageFragment.kt
  app/src/main/res/layout/activity_contact_detail.xml
Labels: enhancement

#31 add gridlayout change event
  app/src/main/java/com/example/limjinlok/ContactDetailActivity.kt
  app/src/main/java/com/example/limjinlok/ContactListAdapter.kt
  app/src/main/java/com/example/limjinlok/ContactListFragment.kt
  app/src/main/java/com/example/limjinlok/ContactViewHolder.kt
  app/src/main/java/com/example/limjinlok/ContactViewHolderGrid.kt
  app/src/main/java/com/example/limjinlok/ContactViewHolderOdd.kt
  app/src/main/java/com/example/limjinlok/MainActivity.kt
  app/src/main/res/drawable/icon_grid.xml
  app/src/main/res/drawable/icon_headline.xml
  app/src/main/res/layout/activity_contact_detail.xml
  app/src/main/res/layout/dialog.xml
  app/src/main/res/layout/fragment_contactlist.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_contactlist.xml
  app/src/main/res/layout/item_contactlist_grid.xml
  app/src/main/res/layout/item_contactlist_odd.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#32 UI Modify
  app/src/main/java/com/example/limjinlok/MainActivity.kt
  app/src/main/res/layout/activity_contact_detail.xml
  app/src/main/res/layout/dialog.xml
  app/src/main/res/layout/item_page.xml
Labels: documentation
